---
#tasks playbook role1
  
- name: Print all available facts
  ansible.builtin.debug:
    var: ansible_facts

- name: Create directory for ansible custom facts
  ansible.builtin.file:
    state: directory
    recurse: true
    path: /etc/ansible/facts.d
  when: _vartemplate is defined

- name: install custom impi fact
  ansible.builtin.copy:
  #template: 
    #remote_src: true 
    remote_src: false
    src: ipmi.fact.j2 
    dest: /etc/ansible/facts.d/ipmi.fact 
  register: config_status
  when: _vartemplate is defined

- name: Re-read facts after adding custom fact
  ansible.builtin.setup:
    filter: ansible_local
  when: _vartemplate is defined