---
#tasks playbook role1
  
- name: Print all available facts
  ansible.builtin.debug:
    var: ansible_facts

- name: Create directory to copy template 
  ansible.builtin.file:
    state: directory
    recurse: true
    path: /home/ansible/configs
  when: _vartemplate is defined

- name: copy jinja file 
  ansible.builtin.template:
    src: srctemplate.j2
    dest: /home/ansible/configs/config1.conf 
    mode: '0644'
  when: _vartemplate is defined

  
- name: Install apache
  apt:
    name: apache2
    state: latest
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
 
- name: Install httpd
  yum:
    name: httpd
    state: latest
  when: ansible_distribution == 'RedHat'